apiVersion: v1
kind: PersistentVolume
metadata:
  name: block-pv
spec:
  capacity:
    storage: 100Mi
  volumeMode: Block
  accessModes:
    - ReadWriteOnce
  storageClassName: manual-block
  hostPath:
    path: /var/tmp/blockfile
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-pvc
  namespace: block-world
spec:
  volumeMode: Block
  accessModes:
    - ReadWriteOnce
  storageClassName: manual-block
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: block-pod
  namespace: block-world
spec:
  containers:
    - name: block-container
      image: busybox
      command: ["sleep", "3600"]
      volumeDevices:
        - devicePath: /dev/xvda
          name: vol
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: block-pvc
