kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-qa-only
  namespace: k2-prod
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          env: qa
