apiVersion: v1
kind: Pod
metadata:
  labels:
    run: preferred-pod
  name: preferred-pod
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 50
        preference:
          matchExpressions:
          - key: disk
            operator: In
            values:
            - ssd
  containers:
  - image: nginx:alpine
    name: preferred-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
