kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

# Use the local cache container (running with host networking in OrbStack).
# From inside containers, macOS is reachable at host.docker.internal.
containerdConfigPatches:
	- |-
		[plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
			endpoint = ["http://host.docker.internal:5001"]
		[plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry-1.docker.io"]
			endpoint = ["http://host.docker.internal:5001"]

		[plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.k8s.io"]
			endpoint = ["http://host.docker.internal:5002"]

		[plugins."io.containerd.grpc.v1.cri".registry.mirrors."ghcr.io"]
			endpoint = ["http://host.docker.internal:5003"]

		[plugins."io.containerd.grpc.v1.cri".registry.mirrors."quay.io"]
			endpoint = ["http://host.docker.internal:5004"]

nodes:
- role: control-plane
- role: worker
- role: worker
