apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-12-27T15:57:28Z"
  generation: 1
  labels:
    run: cassini
  name: cassini
  namespace: mission-control
  resourceVersion: "20627"
  uid: f9b331f8-81ac-4c84-95ff-b225137528ab
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: cassini
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-xcffc
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeSelector:
    kubernetes.io/hostname: ubukubu-node-1
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: "radiation"
    operator: Equal
    value: "high"
  - key: radiation
  volumes:
  - name: kube-api-access-xcffc
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-12-27T15:57:28Z"
    message: '0/3 nodes are available: 1 node(s) didn''t match Pod''s node affinity/selector,
      2 node(s) had untolerated taint(s). no new claims to deallocate, preemption:
      0/3 nodes are available: 3 Preemption is not helpful for scheduling.'
    observedGeneration: 1
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: BestEffort
