apiVersion: v1
kind: Pod
metadata:
  name: business-app
spec:
  volumes:
  - name: shared-data
    emptyDir: {}                         #1
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html   #2
  - name: sidecar
    image: busybox:latest
    volumeMounts:
    - name: shared-data
      mountPath: /data         

For readonly, readOnly: true (.spec.container[].volumeMounts[].readOnly) can be added under the volumeMounts section.

  