apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ckad-gateway
  namespace: default
spec:
  gatewayClassName: my-gateway-class
  listeners:
  - name: http
    protocol: HTTP
    port: 80