apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: color-route
  namespace: gateway-drill
spec:
  parentRefs:
  - name: main-gateway
  hostnames:
  - "colors.example.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: color-service
      port: 80