apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: archive-pvc
  namespace: reclaim-ns
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Mi