apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-app
  name: web-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: web-app
  type: NodePort
status:
  loadBalancer: {}
