apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"NetworkPolicy","metadata":{"annotations":{},"name":"magnetic-storm","namespace":"atlantic"},"spec":{"podSelector":{},"policyTypes":["Ingress"]}}
  creationTimestamp: "2025-12-29T03:10:32Z"
  generation: 1
  name: magnetic-storm
  namespace: atlantic
  resourceVersion: "11155"
  uid: 218f8281-c47a-440b-bfa1-5b54d715e34d
spec:
  podSelector: {}
  policyTypes:
  - Ingress
