apiVersion: v1
kind: Pod
metadata:
  name: webapp
  namespace: crashloop-ns
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 60
    image: nginx:alpine
    imagePullPolicy: IfNotPresent
    name: nginx
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
