apiVersion: v1
kind: Namespace
metadata:
  name: todo
---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: todo-db
  namespace: todo
spec:
  teamId: todo
  volume:
    size: 1Gi
    storageClass: local-path
  numberOfInstances: 3
  users:
    todo:
    - superuser
    - createdb
  databases:
    todo: todo
  postgresql:
    version: "14"
---
apiVersion: v1
kind: Service
metadata:
  name: todo
  namespace: todo
  labels:
    app: todo
spec:
  selector:
    app: todo
  ports:
  - name: web
    protocol: TCP
    port: 5000
    targetPort: 5000
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: todo
  namespace: todo
  labels:
    app: todo
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 30%
      maxSurge: 50%
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: bookofkubernetes/todo:1.0.2
        env:
        - name: NODE_ENV
          value: production
        - name: PREFIX
          value: /todo
        - name: PGHOST
          value: todo-db
        - name: PGDATABASE
          value: todo
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: todo.todo-db.credentials.postgresql.acid.zalan.do
              key: username
              optional: false
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: todo.todo-db.credentials.postgresql.acid.zalan.do
              key: password
              optional: false
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - name: web
          containerPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ingress
  namespace: todo
spec:
  rules:
    - http:
        paths:
          - path: /todo
            pathType: Prefix
            backend:
              service:
                name: todo
                port:
                  number: 5000
