apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manual-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: manual-pv
