kind: Pod
apiVersion: v1
metadata:
  name: nginx
spec:
  restartPolicy: Always
  volumes:
    - name: data
      emptyDir: {}
  initContainers:
  - name: nginx-init
    image: debian:bookworm-slim
    command: ["/bin/sh", "-c"]
    args: ["apt-get update && apt-get install -y cowsay && echo \"<pre>$(/usr/games/cowsay -b 'Hello Kubernetes')</pre>\" > /data/index.html"]
    volumeMounts:                        
    - name: data
      mountPath: /data
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - name: data
      mountPath: /usr/share/nginx/html