apiVersion: v1
kind: Pod
metadata:
  labels:
    run: log-pod
  name: log-pod
spec:
  containers:
  - command: ["/bin/sh", "-c"]
    args:
    - while true; do date >> /var/log/app.log; sleep 1; done
    image: busybox
    name: log-pod
    volumeMounts:
    - mountPath: /var/log
      name: log-vol
  - command: ["/bin/sh", "-c"]
    args:
    - tail -f /var/log/app.log
    image: busybox
    name: sidecar
    volumeMounts:
    - mountPath: /var/log
      name: log-vol
  volumes:
  - emptyDir: {}
    name: log-vol
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
