apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-pv
spec:
  capacity:       
    storage: 1Gi   
  accessModes:     
    - ReadWriteOnce
  hostPath:
    path: /var/logs
    type: DirectoryOrCreate