apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"ghost"},"name":"phantom","namespace":"haunted"},"spec":{"ports":[{"name":"80-80","port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"ghost"},"type":"ClusterIP"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2026-01-01T00:55:28Z"
  labels:
    app: ghost
  name: phantom
  namespace: haunted
  resourceVersion: "8304"
  uid: 4afcc89f-4a69-4d72-a241-1bff8dcefbf1
spec:
  clusterIP: 10.110.172.237
  clusterIPs:
  - 10.110.172.237
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ghost
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
