apiVersion: v1
kind: Pod
metadata:
  labels:
    run: log-pod
  name: log-pod
spec:
  containers:
  - image: busybox
    name: log-pod
    resources: {}
  - image: busybox
    name: sidecar
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
