apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"port-test-svc","namespace":"default"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":8080}],"selector":{"app":"port-test"}}}
  creationTimestamp: "2026-01-09T11:22:20Z"
  name: port-test-svc
  namespace: default
  resourceVersion: "210611"
  uid: 8baea86f-8321-4da2-82e8-0fba42f497d0
spec:
  clusterIP: 10.106.150.206
  clusterIPs:
  - 10.106.150.206
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: port-test
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
