apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"precious-app","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"precious"}},"template":{"metadata":{"labels":{"app":"precious"}},"spec":{"containers":[{"image":"nginx:alpine","name":"nginx"}],"nodeSelector":{"type":"restricted"}}}}}
  creationTimestamp: "2026-01-05T10:23:58Z"
  generation: 2
  name: precious-app
  namespace: default
  resourceVersion: "33226"
  uid: f2ddb05c-3978-4ffa-80c8-2a7e1d80f78d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: precious
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: precious
    spec:
      containers:
      - image: nginx:alpine
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        type: restricted
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: restricted
        value: "true"
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2026-01-05T10:36:46Z"
    lastUpdateTime: "2026-01-05T10:36:46Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-01-05T10:36:43Z"
    lastUpdateTime: "2026-01-05T10:36:46Z"
    message: ReplicaSet "precious-app-59b88d7b49" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
