apiVersion: v1
kind: Pod
metadata:
  name: web-server
  namespace: default
spec:
  restartPolicy: Always
  containers:
  - name: main-app
    image: busybox
    command: ["/bin/sh"]
    args: 
    - -c
    - |
      while true; do
        echo "$(date) - Request served" >> /var/log/web.log;
        sleep 5;
      done
    volumeMounts:
    - mountPath: /var/log
      name: log-vol
  - name: log-shipper
    image: busybox
    restartPolicy: Always
    command: ["/bin/sh", "-c", "tail -f /var/log/web.log"]
    volumeMounts:
    - mountPath: /var/log
      name: log-vol
  volumes:
  - emptyDir: {}
    name: log-vol