---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: temp-store
  name: temp-store
spec:
  containers:
  - image: busybox
    command: ["/bin/sleep", "3600"]
    name: temp-store
    resources: {}
    volumeMounts:
    - mountPath: /scratch
      name: scratch-vol
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: scratch-vol
    ephemeral:
      volumeClaimTemplate:
        metadata:
          labels:
            type: frontend
        spec:
          accessModes: ["ReadWriteOnce"]  
          storageClassName: "scratch"
          resources:
            requests:
              storage: 10Mi
status: {}
