apiVersion: v1
kind: Pod
metadata:
  labels:
    run: web-app
  name: web-app
  namespace: app-team
spec:
  containers:
  - image: nginx:latest
    name: web-app
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
